// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stocks.DB;

#nullable disable

namespace Stock.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231114175734_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Stocks.Models.ResponseData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Close")
                        .HasColumnType("REAL");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("High")
                        .HasColumnType("REAL");

                    b.Property<double?>("Low")
                        .HasColumnType("REAL");

                    b.Property<double?>("Open")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeSeries")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volume")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
